# export AUTH_TYPE=''
# export CONTENT_LENGTH='3'
# export CONTENT_TYPE=''
# export GATEWAY_INTERFACE=''
# export PATH_INFO='/directory/youpi.bla'
# export PATH_TRANSLATED=''
# export QUERY_STRING=''
# export REMOTE_ADDR=''
# export REMOTE_IDENT=''
# export REMOTE_USER=''
# export REQUEST_METHOD='POST'
# export REQUEST_URI='/directory/youpi.bla'
# export SCRIPT_NAME='cgi_tester'
# export SERVER_NAME='webser/1.1'
# export SERVER_PORT='5005'
# export SERVER_PROTOCOL='HTTP/1.1'
# export SERVER_SOFTWARE=''
# export HTTP_VERSION=1.1
# export HTTP_ACCEPT_ENCODING=gzip
# export HTTP_CONTENT_TYPE=test/file
# export HTTP_HOST=localhost:5005
# export HTTP_TRANSFER_ENCODING=chunked
# export HTTP_USER_AGENT=Go-http-client/1.1
# export HTTP_X_SECRET_HEADER_FOR_TEST=h

export AUTH_TYPE=Accept
export CONTENT_LENGTH=1
export CONTENT_TYPE=text/plain
export GATEWAY_INTERFACE=CGI/1.1
export HTTP_ACCEPT_ENCODING=gzip
export HTTP_CONTENT_TYPE=test/file
export HTTP_HOST=127.0.0.1:8888
export HTTP_TRANSFER_ENCODING=chunked
export HTTP_USER_AGENT=Go-http-client/1.1
export PATH_INFO=/directory/youpi.bla
export PATH_TRANSLATED=/tmp/www/YoupiBanane/youpi.bla
export QUERY_STRING=''
export REMOTE_ADDR=127.0.0.1
export REMOTE_IDENT=''
export REMOTE_USER=''
export REQUEST_METHOD=POST
export REQUEST_URI=/directory/youpi.bla
export SCRIPT_NAME=ubuntu_cgi_tester
export SERVER_NAME=127.0.0.1
export SERVER_PORT=8888
export SERVER_PROTOCOL=HTTP/1.1
export SERVER_SOFTWARE=webserv s19


./ubuntu_cgi_tester